### ISSUE TITLE
Can we rename proposal-intl-temporal to something different from temporal? it might cause confusion in TG1

### ISSUE THREAD

**Issue by FrankYFTang** [FrankYFTang/proposal-intl-era-monthcode#3]
In TG2 2022-10-06 @romulocintra raise this issue. 
We decided to rename this proposal to "Intl era and monthCode proposal"

**Comment by sffc** [comment]
TG2 discussion: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-10-06.md#can-we-rename-proposal-intl-temporal
